
# 텐서(Tensor)

텐서에 대한 설명을 여러개 읽어봤는데 개인적으로 그냥 데이터를 나타내는 다차원의 행렬 정도라도 생각하기로 했다. 0차원이면 스칼라, 1차원이면 벡터 형태 등...

In [ ]:
import torch
import numpy as np

## 텐서(tensor) 초기화



**데이터로부터 직접(directly) 생성하기**

데이터로부터 직접 텐서를 생성할 수 있습니다. 데이터의 자료형(data type)은 자동으로 유추합니다.



In [ ]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

**NumPy 배열로부터 생성하기**

텐서는 NumPy 배열로 생성할 수 있습니다. (그 반대도 가능합니다 - `bridge-to-np-label` 참고)



In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**다른 텐서로부터 생성하기:**

명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(모양(shape), 자료형(datatype))을 유지합니다.



In [ ]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지합니다.
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씁니다.
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8844, 0.1980],
        [0.4653, 0.3314]]) 



**무작위(random) 또는 상수(constant) 값을 사용하기:**

``shape`` 은 텐서의 차원(dimension)을 나타내는 튜플(tuple)로, 아래 함수들에서는 출력 텐서의 차원을 결정합니다.



In [ ]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3568, 0.5438, 0.8488],
        [0.8330, 0.1274, 0.4803]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


--------------




## 텐서의 속성(Attribute)

텐서의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지(device)를 나타냅니다.



In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


--------------




## 텐서 연산(Operation)


각 연산들은 (일반적으로 CPU보다 빠른) GPU에서 실행할 수 있습니다. Colab을 사용한다면,
Edit > Notebook Settings 에서 GPU를 할당할 수 있습니다.

기본적으로 텐서는 CPU에 생성됩니다. ``.to`` 메소드를 사용하면 (GPU의 가용성(availability)을 확인한 뒤)
GPU로 텐서를 명시적으로 이동할 수 있습니다. 장치들 간에 큰 텐서들을 복사하는 것은 시간과 메모리 측면에서 비용이
많이든다는 것을 기억하세요!



In [ ]:
# GPU가 존재하면 텐서를 이동합니다
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

목록에서 몇몇 연산들을 시도해보세요.
NumPy API에 익숙하다면 Tensor API를 사용하는 것은 식은 죽 먹기라는 것을 알게 되실 겁니다.




**NumPy식의 표준 인덱싱과 슬라이싱:**



In [ ]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**텐서 합치기** ``torch.cat`` 을 사용하여 주어진 차원에 따라 일련의 텐서를 연결할 수 있습니다.
``torch.cat`` 과 미묘하게 다른 또 다른 텐서 결합 연산인
[torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html)_ 도 참고해보세요.



In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


**산술 연산(Arithmetic operations)**



In [ ]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
# ``tensor.T`` 는 텐서의 전치(transpose)를 반환합니다.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)


# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

**단일-요소(single-element) 텐서** 텐서의 모든 값을 하나로 집계(aggregate)하여 요소가 하나인 텐서의 경우,
``item()`` 을 사용하여 Python 숫자 값으로 변환할 수 있습니다:



In [ ]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


**바꿔치기(in-place) 연산**
연산 결과를 피연산자(operand)에 저장하는 연산을 바꿔치기 연산이라고 부르며, ``_`` 접미사를 갖습니다.
예를 들어: ``x.copy_(y)`` 나 ``x.t_()`` 는 ``x`` 를 변경합니다.



In [ ]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


<div class="alert alert-info"><h4>Note</h4><p>바꿔치기 연산은 메모리를 일부 절약하지만, 기록(history)이 즉시 삭제되어 도함수(derivative) 계산에 문제가 발생할 수 있습니다.
     따라서, 사용을 권장하지 않습니다.</p></div>



--------------





## NumPy 변환(Bridge)
CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.



개인적으로 텐서와 넘파이가 조금 헷갈려서 관련 내용을 조금 찾아봤습니다.

##Numpy와 Tensor의 비교##
공통점

1. 데이터 저장: 둘 다 다차원 배열 형태로 데이터를 저장할 수 있습니다.
2. 연산 지원: 둘 다 다양한 수학적 연산과 선형 대수 연산을 지원합니다.
3.  슬라이싱 및 인덱싱: 둘 다 배열의 특정 부분을 선택하고 조작하는 슬라이싱 및 인덱싱 기능을 제공합니다.

차이점

1. 호환성 및 생태계:

- 넘파이 배열: 과학 계산과 데이터 분석에 널리 사용되며, 판다스(Pandas), 사이킷런(Scikit-learn) 등 다양한 파이썬 라이브러리와 잘 통합됩니다.

- 파이토치 텐서: 주로 딥러닝 및 머신러닝 작업에 사용되며, GPU 가속을 지원하여 대규모 신경망 훈련에 적합합니다. 텐서플로우(TensorFlow)의 텐서와도 비슷한 개념입니다.

2. 연산 장치(GPU 지원):

- 넘파이 배열: CPU에서만 연산이 가능합니다.
- 파이토치 텐서: CPU와 GPU 모두에서 연산이 가능하며, GPU를 사용하면 대규모 연산을 더욱 빠르게 처리할 수 있습니다. GPU로 이동시키기 위해 .to('cuda') 또는 .cuda() 메서드를 사용할 수 있습니다.

3. 자동 미분:

- 넘파이 배열: 자동 미분 기능이 없습니다. 수동으로 그라디언트를 계산해야 합니다.
- 파이토치 텐서: 자동 미분을 지원합니다. 텐서를 생성할 때 requires_grad=True로 설정하면, 역전파 시 그라디언트가 자동으로 계산됩니다.

4. 기능 차이:

- 넘파이 배열: 과학 계산과 데이터 분석에 중점을 둔 다양한 함수와 메서드를 제공합니다.
- 파이토치 텐서: 딥러닝 모델 구성 및 학습을 위한 다양한 모듈, 함수, 클래스 등을 포함합니다. 예를 들어, 신경망 층, 손실 함수, 최적화 알고리즘 등이 포함되어 있습니다.


### 텐서를 NumPy 배열로 변환하기



표현했을 때의 차이도 약간 있다는 것을 확인할 수 있었습니다.

In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


텐서의 변경 사항이 NumPy 배열에 반영됩니다.



In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### NumPy 배열을 텐서로 변환하기



In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

NumPy 배열의 변경 사항이 텐서에 반영됩니다.



In [ ]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
